defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: facebook

test:
  <<: *defaults
  database: friends_googlemap_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: friends_googlemap
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
